In [71]:
import nltk
from keras.preprocessing.text import Tokenizer

In [72]:
texts = ['he is a teacher', 'she is a teacher', 'she and he are teachers', 'he is a student and she is a student']
sentences = []
for sent in texts:
  sentences.append(nltk.word_tokenize(sent))
print(sentences)

[['he', 'is', 'a', 'teacher'], ['she', 'is', 'a', 'teacher'], ['she', 'and', 'he', 'are', 'teachers'], ['he', 'is', 'a', 'student', 'and', 'she', 'is', 'a', 'student']]


In [73]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

In [74]:
print(tokenizer.word_index)

{'is': 1, 'a': 2, 'he': 3, 'she': 4, 'teacher': 5, 'and': 6, 'student': 7, 'are': 8, 'teachers': 9}


In [75]:
#he is a teacher
#she is a teacher
#she and he are teachers
#he is a student and she is a student
x = tokenizer.texts_to_matrix(sentences, mode='count')
print(x)

[[0. 1. 1. 1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 1. 0. 1. 1.]
 [0. 2. 2. 1. 1. 0. 1. 2. 0. 0.]]


In [77]:
import pandas as pd

In [76]:
import nltk
import numpy as np

In [78]:
filename = 'spam.csv'
df = pd.read_csv(filename, encoding= 'latin-1')
#df = pd.read_csv(filename, delimiter='\t', header=None, skipinitialspace=True, encoding= 'latin-1')
#df = pd.read_csv(filename, encoding= 'utf-8')
print(df.shape)
print(df.columns)
print(df.head(10))

(5572, 5)
Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')
     v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3   

In [79]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


In [80]:
data =df.values
#print(data[:2])
lines = data[:,1]
labels = data[:,0]
print(lines[:5])
print(labels[:20])

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 'U dun say so early hor... U c already then say...'
 "Nah I don't think he goes to usf, he lives around here though"]
['ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'spam' 'ham'
 'spam' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'spam']


In [81]:
# tách từ trong từng câu
sentences = [nltk.word_tokenize(sent) for sent in lines]
#2-gram
print(sentences[0])

['Go', 'until', 'jurong', 'point', ',', 'crazy', '..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', '...', 'Cine', 'there', 'got', 'amore', 'wat', '...']


In [82]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

#matrix
X = tokenizer.texts_to_matrix(sentences, mode='binary')
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]]


In [83]:
from sklearn.model_selection import train_test_split
x_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=0)

In [84]:
from sklearn.linear_model import LogisticRegression
# thay logistic-regression -> naive bayes, svm
model_LR = LogisticRegression()
model_LR = model_LR.fit(x_train, y_train)

In [85]:
from sklearn.metrics import classification_report
y_pred = model_LR.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       949
        spam       0.99      0.89      0.93       166

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [106]:
input_sent = 'Cao Tran Tuan Duy'

# Step 1: tokenize
input_sentences = []
input_sentences.append(nltk.word_tokenize(input_sent))

print(input_sentences)

#input_sentences = [nltk.word_tokenize(input_sent)]
#print(input_sentences)


# Step 2: chuyển list of tokens -> vector of number

# texts_to_matrix
# tokenizer.texts_to_matrix(input_sentences, mode='binary')


[['Cao', 'Tran', 'Tuan', 'Duy']]


In [107]:
X_input = tokenizer.texts_to_matrix(input_sentences, mode='binary')
print(X_input)

[[0. 0. 0. ... 0. 0. 0.]]


In [108]:
y_pred = model_LR.predict(X_input)
print(y_pred)

['ham']
